# Joker center keys -> display names + rarity.
# Source: Balatro Wiki Module:Jokers/data (extracted from game.lua), 150 base-game jokers.
RARITIES = {1: 'Common', 2: 'Uncommon', 3: 'Rare', 4: 'Legendary'}

_JOKERS = [
    ('j_joker', 'Joker', 1),
    ('j_greedy_joker', 'Greedy Joker', 1),
    ('j_lusty_joker', 'Lusty Joker', 1),
    ('j_wrathful_joker', 'Wrathful Joker', 1),
    ('j_gluttenous_joker', 'Gluttonous Joker', 1),
    ('j_jolly', 'Jolly Joker', 1),
    ('j_zany', 'Zany Joker', 1),
    ('j_mad', 'Mad Joker', 1),
    ('j_crazy', 'Crazy Joker', 1),
    ('j_droll', 'Droll Joker', 1),
    ('j_sly', 'Sly Joker', 1),
    ('j_wily', 'Wily Joker', 1),
    ('j_clever', 'Clever Joker', 1),
    ('j_devious', 'Devious Joker', 1),
    ('j_crafty', 'Crafty Joker', 1),
    ('j_half', 'Half Joker', 1),
    ('j_stencil', 'Joker Stencil', 2),
    ('j_four_fingers', 'Four Fingers', 2),
    ('j_mime', 'Mime', 2),
    ('j_credit_card', 'Credit Card', 1),
    ('j_ceremonial', 'Ceremonial Dagger', 2),
    ('j_banner', 'Banner', 1),
    ('j_mystic_summit', 'Mystic Summit', 1),
    ('j_marble', 'Marble Joker', 2),
    ('j_loyalty_card', 'Loyalty Card', 2),
    ('j_8_ball', '8 Ball', 1),
    ('j_misprint', 'Misprint', 1),
    ('j_dusk', 'Dusk', 2),
    ('j_raised_fist', 'Raised Fist', 1),
    ('j_chaos', 'Chaos the Clown', 1),
    ('j_fibonacci', 'Fibonacci', 2),
    ('j_steel_joker', 'Steel Joker', 2),
    ('j_scary_face', 'Scary Face', 1),
    ('j_abstract', 'Abstract Joker', 1),
    ('j_delayed_grat', 'Delayed Gratification', 1),
    ('j_hack', 'Hack', 2),
    ('j_pareidolia', 'Pareidolia', 2),
    ('j_gros_michel', 'Gros Michel', 1),
    ('j_even_steven', 'Even Steven', 1),
    ('j_odd_todd', 'Odd Todd', 1),
    ('j_scholar', 'Scholar', 1),
    ('j_business', 'Business Card', 1),
    ('j_supernova', 'Supernova', 1),
    ('j_ride_the_bus', 'Ride the Bus', 1),
    ('j_space', 'Space Joker', 2),
    ('j_egg', 'Egg', 1),
    ('j_burglar', 'Burglar', 2),
    ('j_blackboard', 'Blackboard', 2),
    ('j_runner', 'Runner', 1),
    ('j_ice_cream', 'Ice Cream', 1),
    ('j_dna', 'DNA', 3),
    ('j_splash', 'Splash', 1),
    ('j_blue_joker', 'Blue Joker', 1),
    ('j_sixth_sense', 'Sixth Sense', 2),
    ('j_constellation', 'Constellation', 2),
    ('j_hiker', 'Hiker', 2),
    ('j_faceless', 'Faceless Joker', 1),
    ('j_green_joker', 'Green Joker', 1),
    ('j_superposition', 'Superposition', 1),
    ('j_todo_list', 'To Do List', 1),
    ('j_cavendish', 'Cavendish', 1),
    ('j_card_sharp', 'Card Sharp', 2),
    ('j_red_card', 'Red Card', 1),
    ('j_madness', 'Madness', 2),
    ('j_square', 'Square Joker', 1),
    ('j_seance', 'Seance', 2),
    ('j_riff_raff', 'Riff-raff', 1),
    ('j_vampire', 'Vampire', 2),
    ('j_shortcut', 'Shortcut', 2),
    ('j_hologram', 'Hologram', 2),
    ('j_vagabond', 'Vagabond', 3),
    ('j_baron', 'Baron', 3),
    ('j_cloud_9', 'Cloud 9', 2),
    ('j_rocket', 'Rocket', 2),
    ('j_obelisk', 'Obelisk', 3),
    ('j_midas_mask', 'Midas Mask', 2),
    ('j_luchador', 'Luchador', 2),
    ('j_photograph', 'Photograph', 1),
    ('j_gift', 'Gift Card', 2),
    ('j_turtle_bean', 'Turtle Bean', 2),
    ('j_erosion', 'Erosion', 2),
    ('j_reserved_parking', 'Reserved Parking', 1),
    ('j_mail', 'Mail-In Rebate', 1),
    ('j_to_the_moon', 'To the Moon', 2),
    ('j_hallucination', 'Hallucination', 1),
    ('j_fortune_teller', 'Fortune Teller', 1),
    ('j_juggler', 'Juggler', 1),
    ('j_drunkard', 'Drunkard', 1),
    ('j_stone', 'Stone Joker', 2),
    ('j_golden', 'Golden Joker', 1),
    ('j_lucky_cat', 'Lucky Cat', 2),
    ('j_baseball', 'Baseball Card', 3),
    ('j_bull', 'Bull', 2),
    ('j_diet_cola', 'Diet Cola', 2),
    ('j_trading', 'Trading Card', 2),
    ('j_flash', 'Flash Card', 2),
    ('j_popcorn', 'Popcorn', 1),
    ('j_trousers', 'Spare Trousers', 2),
    ('j_ancient', 'Ancient Joker', 3),
    ('j_ramen', 'Ramen', 2),
    ('j_walkie_talkie', 'Walkie Talkie', 1),
    ('j_selzer', 'Seltzer', 2),
    ('j_castle', 'Castle', 2),
    ('j_smiley', 'Smiley Face', 1),
    ('j_campfire', 'Campfire', 3),
    ('j_ticket', 'Golden Ticket', 1),
    ('j_mr_bones', 'Mr. Bones', 2),
    ('j_acrobat', 'Acrobat', 2),
    ('j_sock_and_buskin', 'Sock and Buskin', 2),
    ('j_swashbuckler', 'Swashbuckler', 1),
    ('j_troubadour', 'Troubadour', 2),
    ('j_certificate', 'Certificate', 2),
    ('j_smeared', 'Smeared Joker', 2),
    ('j_throwback', 'Throwback', 2),
    ('j_hanging_chad', 'Hanging Chad', 1),
    ('j_rough_gem', 'Rough Gem', 2),
    ('j_bloodstone', 'Bloodstone', 2),
    ('j_arrowhead', 'Arrowhead', 2),
    ('j_onyx_agate', 'Onyx Agate', 2),
    ('j_glass', 'Glass Joker', 2),
    ('j_ring_master', 'Showman', 2),
    ('j_flower_pot', 'Flower Pot', 2),
    ('j_blueprint', 'Blueprint', 3),
    ('j_wee', 'Wee Joker', 3),
    ('j_merry_andy', 'Merry Andy', 2),
    ('j_oops', 'Oops! All 6s', 2),
    ('j_idol', 'The Idol', 2),
    ('j_seeing_double', 'Seeing Double', 2),
    ('j_matador', 'Matador', 2),
    ('j_hit_the_road', 'Hit the Road', 3),
    ('j_duo', 'The Duo', 3),
    ('j_trio', 'The Trio', 3),
    ('j_family', 'The Family', 3),
    ('j_order', 'The Order', 3),
    ('j_tribe', 'The Tribe', 3),
    ('j_stuntman', 'Stuntman', 3),
    ('j_invisible', 'Invisible Joker', 3),
    ('j_brainstorm', 'Brainstorm', 3),
    ('j_satellite', 'Satellite', 2),
    ('j_shoot_the_moon', 'Shoot the Moon', 1),
    ('j_drivers_license', "Driver's License", 3),
    ('j_cartomancer', 'Cartomancer', 2),
    ('j_astronomer', 'Astronomer', 2),
    ('j_burnt', 'Burnt Joker', 3),
    ('j_bootstraps', 'Bootstraps', 2),
    ('j_caino', 'Caino', 4),
    ('j_triboulet', 'Triboulet', 4),
    ('j_yorick', 'Yorick', 4),
    ('j_chicot', 'Chicot', 4),
    ('j_perkeo', 'Perkeo', 4),
]

CATALOG = [{'key': k, 'name': n, 'rarity': r, 'rarity_name': RARITIES[r]} for k, n, r in _JOKERS]
NAMES = {k: n for k, n, r in _JOKERS}


def name_for(center):
    return NAMES.get(center, center)
