# Joker center keys -> display name, rarity, order, cost, set, config.
# Generated from the Balatro Wiki Module:Jokers/data. Regenerate with:
#   python build-scripts/gen_joker_catalog.py
RARITIES = {1: 'Common', 2: 'Uncommon', 3: 'Rare', 4: 'Legendary'}

_JOKERS = [
    {'key': 'j_joker', 'name': 'Joker', 'rarity': 1, 'order': 1, 'cost': 2, 'set': 'Joker', 'config': {'mult': 4}},
    {'key': 'j_greedy_joker', 'name': 'Greedy Joker', 'rarity': 1, 'order': 2, 'cost': 5, 'set': 'Joker', 'config': {'extra': {'s_mult': 3, 'suit': 'Diamonds'}}},
    {'key': 'j_lusty_joker', 'name': 'Lusty Joker', 'rarity': 1, 'order': 3, 'cost': 5, 'set': 'Joker', 'config': {'extra': {'s_mult': 3, 'suit': 'Hearts'}}},
    {'key': 'j_wrathful_joker', 'name': 'Wrathful Joker', 'rarity': 1, 'order': 4, 'cost': 5, 'set': 'Joker', 'config': {'extra': {'s_mult': 3, 'suit': 'Spades'}}},
    {'key': 'j_gluttenous_joker', 'name': 'Gluttonous Joker', 'rarity': 1, 'order': 5, 'cost': 5, 'set': 'Joker', 'config': {'extra': {'s_mult': 3, 'suit': 'Clubs'}}},
    {'key': 'j_jolly', 'name': 'Jolly Joker', 'rarity': 1, 'order': 6, 'cost': 3, 'set': 'Joker', 'config': {'t_mult': 8, 'type': 'Pair'}},
    {'key': 'j_zany', 'name': 'Zany Joker', 'rarity': 1, 'order': 7, 'cost': 4, 'set': 'Joker', 'config': {'t_mult': 12, 'type': 'Three of a Kind'}},
    {'key': 'j_mad', 'name': 'Mad Joker', 'rarity': 1, 'order': 8, 'cost': 4, 'set': 'Joker', 'config': {'t_mult': 10, 'type': 'Two Pair'}},
    {'key': 'j_crazy', 'name': 'Crazy Joker', 'rarity': 1, 'order': 9, 'cost': 4, 'set': 'Joker', 'config': {'t_mult': 12, 'type': 'Straight'}},
    {'key': 'j_droll', 'name': 'Droll Joker', 'rarity': 1, 'order': 10, 'cost': 4, 'set': 'Joker', 'config': {'t_mult': 10, 'type': 'Flush'}},
    {'key': 'j_sly', 'name': 'Sly Joker', 'rarity': 1, 'order': 11, 'cost': 3, 'set': 'Joker', 'config': {'t_chips': 50, 'type': 'Pair'}},
    {'key': 'j_wily', 'name': 'Wily Joker', 'rarity': 1, 'order': 12, 'cost': 4, 'set': 'Joker', 'config': {'t_chips': 100, 'type': 'Three of a Kind'}},
    {'key': 'j_clever', 'name': 'Clever Joker', 'rarity': 1, 'order': 13, 'cost': 4, 'set': 'Joker', 'config': {'t_chips': 80, 'type': 'Two Pair'}},
    {'key': 'j_devious', 'name': 'Devious Joker', 'rarity': 1, 'order': 14, 'cost': 4, 'set': 'Joker', 'config': {'t_chips': 100, 'type': 'Straight'}},
    {'key': 'j_crafty', 'name': 'Crafty Joker', 'rarity': 1, 'order': 15, 'cost': 4, 'set': 'Joker', 'config': {'t_chips': 80, 'type': 'Flush'}},
    {'key': 'j_half', 'name': 'Half Joker', 'rarity': 1, 'order': 16, 'cost': 5, 'set': 'Joker', 'config': {'extra': {'mult': 20, 'size': 3}}},
    {'key': 'j_stencil', 'name': 'Joker Stencil', 'rarity': 2, 'order': 17, 'cost': 8, 'set': 'Joker', 'config': {}},
    {'key': 'j_four_fingers', 'name': 'Four Fingers', 'rarity': 2, 'order': 18, 'cost': 7, 'set': 'Joker', 'config': {}},
    {'key': 'j_mime', 'name': 'Mime', 'rarity': 2, 'order': 19, 'cost': 5, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_credit_card', 'name': 'Credit Card', 'rarity': 1, 'order': 20, 'cost': 1, 'set': 'Joker', 'config': {'extra': 20}},
    {'key': 'j_ceremonial', 'name': 'Ceremonial Dagger', 'rarity': 2, 'order': 21, 'cost': 6, 'set': 'Joker', 'config': {'mult': 0}},
    {'key': 'j_banner', 'name': 'Banner', 'rarity': 1, 'order': 22, 'cost': 5, 'set': 'Joker', 'config': {'extra': 30}},
    {'key': 'j_mystic_summit', 'name': 'Mystic Summit', 'rarity': 1, 'order': 23, 'cost': 5, 'set': 'Joker', 'config': {'extra': {'mult': 15, 'd_remaining': 0}}},
    {'key': 'j_marble', 'name': 'Marble Joker', 'rarity': 2, 'order': 24, 'cost': 6, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_loyalty_card', 'name': 'Loyalty Card', 'rarity': 2, 'order': 25, 'cost': 5, 'set': 'Joker', 'config': {'extra': {'Xmult': 4, 'every': 5, 'remaining': '5 remaining'}}},
    {'key': 'j_8_ball', 'name': '8 Ball', 'rarity': 1, 'order': 26, 'cost': 5, 'set': 'Joker', 'config': {'extra': 4}},
    {'key': 'j_misprint', 'name': 'Misprint', 'rarity': 1, 'order': 27, 'cost': 4, 'set': 'Joker', 'config': {'extra': {'max': 23, 'min': 0}}},
    {'key': 'j_dusk', 'name': 'Dusk', 'rarity': 2, 'order': 28, 'cost': 5, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_raised_fist', 'name': 'Raised Fist', 'rarity': 1, 'order': 29, 'cost': 5, 'set': 'Joker', 'config': {}},
    {'key': 'j_chaos', 'name': 'Chaos the Clown', 'rarity': 1, 'order': 30, 'cost': 4, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_fibonacci', 'name': 'Fibonacci', 'rarity': 2, 'order': 31, 'cost': 8, 'set': 'Joker', 'config': {'extra': 8}},
    {'key': 'j_steel_joker', 'name': 'Steel Joker', 'rarity': 2, 'order': 32, 'cost': 7, 'set': 'Joker', 'config': {'extra': 0.2}},
    {'key': 'j_scary_face', 'name': 'Scary Face', 'rarity': 1, 'order': 33, 'cost': 4, 'set': 'Joker', 'config': {'extra': 30}},
    {'key': 'j_abstract', 'name': 'Abstract Joker', 'rarity': 1, 'order': 34, 'cost': 4, 'set': 'Joker', 'config': {'extra': 3}},
    {'key': 'j_delayed_grat', 'name': 'Delayed Gratification', 'rarity': 1, 'order': 35, 'cost': 4, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_hack', 'name': 'Hack', 'rarity': 2, 'order': 36, 'cost': 6, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_pareidolia', 'name': 'Pareidolia', 'rarity': 2, 'order': 37, 'cost': 5, 'set': 'Joker', 'config': {}},
    {'key': 'j_gros_michel', 'name': 'Gros Michel', 'rarity': 1, 'order': 38, 'cost': 5, 'set': 'Joker', 'config': {'extra': {'odds': 6, 'mult': 15}}},
    {'key': 'j_even_steven', 'name': 'Even Steven', 'rarity': 1, 'order': 39, 'cost': 4, 'set': 'Joker', 'config': {'extra': 4}},
    {'key': 'j_odd_todd', 'name': 'Odd Todd', 'rarity': 1, 'order': 40, 'cost': 4, 'set': 'Joker', 'config': {'extra': 31}},
    {'key': 'j_scholar', 'name': 'Scholar', 'rarity': 1, 'order': 41, 'cost': 4, 'set': 'Joker', 'config': {'extra': {'mult': 4, 'chips': 20}}},
    {'key': 'j_business', 'name': 'Business Card', 'rarity': 1, 'order': 42, 'cost': 4, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_supernova', 'name': 'Supernova', 'rarity': 1, 'order': 43, 'cost': 5, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_ride_the_bus', 'name': 'Ride the Bus', 'rarity': 1, 'order': 44, 'cost': 6, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_space', 'name': 'Space Joker', 'rarity': 2, 'order': 45, 'cost': 5, 'set': 'Joker', 'config': {'extra': 4}},
    {'key': 'j_egg', 'name': 'Egg', 'rarity': 1, 'order': 46, 'cost': 4, 'set': 'Joker', 'config': {'extra': 3}},
    {'key': 'j_burglar', 'name': 'Burglar', 'rarity': 2, 'order': 47, 'cost': 6, 'set': 'Joker', 'config': {'extra': 3}},
    {'key': 'j_blackboard', 'name': 'Blackboard', 'rarity': 2, 'order': 48, 'cost': 6, 'set': 'Joker', 'config': {'extra': 3}},
    {'key': 'j_runner', 'name': 'Runner', 'rarity': 1, 'order': 49, 'cost': 5, 'set': 'Joker', 'config': {'extra': {'chips': 0, 'chip_mod': 15}}},
    {'key': 'j_ice_cream', 'name': 'Ice Cream', 'rarity': 1, 'order': 50, 'cost': 5, 'set': 'Joker', 'config': {'extra': {'chips': 100, 'chip_mod': 5}}},
    {'key': 'j_dna', 'name': 'DNA', 'rarity': 3, 'order': 51, 'cost': 8, 'set': 'Joker', 'config': {}},
    {'key': 'j_splash', 'name': 'Splash', 'rarity': 1, 'order': 52, 'cost': 3, 'set': 'Joker', 'config': {}},
    {'key': 'j_blue_joker', 'name': 'Blue Joker', 'rarity': 1, 'order': 53, 'cost': 5, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_sixth_sense', 'name': 'Sixth Sense', 'rarity': 2, 'order': 54, 'cost': 6, 'set': 'Joker', 'config': {}},
    {'key': 'j_constellation', 'name': 'Constellation', 'rarity': 2, 'order': 55, 'cost': 6, 'set': 'Joker', 'config': {'extra': 0.1, 'Xmult': 1}},
    {'key': 'j_hiker', 'name': 'Hiker', 'rarity': 2, 'order': 56, 'cost': 5, 'set': 'Joker', 'config': {'extra': 5}},
    {'key': 'j_faceless', 'name': 'Faceless Joker', 'rarity': 1, 'order': 57, 'cost': 4, 'set': 'Joker', 'config': {'extra': {'dollars': 5, 'faces': 3}}},
    {'key': 'j_green_joker', 'name': 'Green Joker', 'rarity': 1, 'order': 58, 'cost': 4, 'set': 'Joker', 'config': {'extra': {'hand_add': 1, 'discard_sub': 1}}},
    {'key': 'j_superposition', 'name': 'Superposition', 'rarity': 1, 'order': 59, 'cost': 4, 'set': 'Joker', 'config': {}},
    {'key': 'j_todo_list', 'name': 'To Do List', 'rarity': 1, 'order': 60, 'cost': 4, 'set': 'Joker', 'config': {'extra': {'dollars': 4, 'poker_hand': 'High Card'}}},
    {'key': 'j_cavendish', 'name': 'Cavendish', 'rarity': 1, 'order': 61, 'cost': 4, 'set': 'Joker', 'config': {'extra': {'odds': 1000, 'Xmult': 3}}},
    {'key': 'j_card_sharp', 'name': 'Card Sharp', 'rarity': 2, 'order': 62, 'cost': 6, 'set': 'Joker', 'config': {'extra': {'Xmult': 3}}},
    {'key': 'j_red_card', 'name': 'Red Card', 'rarity': 1, 'order': 63, 'cost': 5, 'set': 'Joker', 'config': {'extra': 3}},
    {'key': 'j_madness', 'name': 'Madness', 'rarity': 2, 'order': 64, 'cost': 7, 'set': 'Joker', 'config': {'extra': 0.5}},
    {'key': 'j_square', 'name': 'Square Joker', 'rarity': 1, 'order': 65, 'cost': 4, 'set': 'Joker', 'config': {'extra': {'chips': 0, 'chip_mod': 4}}},
    {'key': 'j_seance', 'name': 'Seance', 'rarity': 2, 'order': 66, 'cost': 6, 'set': 'Joker', 'config': {'extra': {'poker_hand': 'Straight Flush'}}},
    {'key': 'j_riff_raff', 'name': 'Riff-raff', 'rarity': 1, 'order': 67, 'cost': 6, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_vampire', 'name': 'Vampire', 'rarity': 2, 'order': 68, 'cost': 7, 'set': 'Joker', 'config': {'extra': 0.1, 'Xmult': 1}},
    {'key': 'j_shortcut', 'name': 'Shortcut', 'rarity': 2, 'order': 69, 'cost': 7, 'set': 'Joker', 'config': {}},
    {'key': 'j_hologram', 'name': 'Hologram', 'rarity': 2, 'order': 70, 'cost': 7, 'set': 'Joker', 'config': {'extra': 0.25, 'Xmult': 1}},
    {'key': 'j_vagabond', 'name': 'Vagabond', 'rarity': 3, 'order': 71, 'cost': 8, 'set': 'Joker', 'config': {'extra': 4}},
    {'key': 'j_baron', 'name': 'Baron', 'rarity': 3, 'order': 72, 'cost': 8, 'set': 'Joker', 'config': {'extra': 1.5}},
    {'key': 'j_cloud_9', 'name': 'Cloud 9', 'rarity': 2, 'order': 73, 'cost': 7, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_rocket', 'name': 'Rocket', 'rarity': 2, 'order': 74, 'cost': 6, 'set': 'Joker', 'config': {'extra': {'dollars': 1, 'increase': 2}}},
    {'key': 'j_obelisk', 'name': 'Obelisk', 'rarity': 3, 'order': 75, 'cost': 8, 'set': 'Joker', 'config': {'extra': 0.2, 'Xmult': 1}},
    {'key': 'j_midas_mask', 'name': 'Midas Mask', 'rarity': 2, 'order': 76, 'cost': 7, 'set': 'Joker', 'config': {}},
    {'key': 'j_luchador', 'name': 'Luchador', 'rarity': 2, 'order': 77, 'cost': 5, 'set': 'Joker', 'config': {}},
    {'key': 'j_photograph', 'name': 'Photograph', 'rarity': 1, 'order': 78, 'cost': 5, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_gift', 'name': 'Gift Card', 'rarity': 2, 'order': 79, 'cost': 6, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_turtle_bean', 'name': 'Turtle Bean', 'rarity': 2, 'order': 80, 'cost': 6, 'set': 'Joker', 'config': {'extra': {'h_size': 5, 'h_mod': 1}}},
    {'key': 'j_erosion', 'name': 'Erosion', 'rarity': 2, 'order': 81, 'cost': 6, 'set': 'Joker', 'config': {'extra': 4}},
    {'key': 'j_reserved_parking', 'name': 'Reserved Parking', 'rarity': 1, 'order': 82, 'cost': 6, 'set': 'Joker', 'config': {'extra': {'odds': 2, 'dollars': 1}}},
    {'key': 'j_mail', 'name': 'Mail-In Rebate', 'rarity': 1, 'order': 83, 'cost': 4, 'set': 'Joker', 'config': {'extra': 5}},
    {'key': 'j_to_the_moon', 'name': 'To the Moon', 'rarity': 2, 'order': 84, 'cost': 5, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_hallucination', 'name': 'Hallucination', 'rarity': 1, 'order': 85, 'cost': 4, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_fortune_teller', 'name': 'Fortune Teller', 'rarity': 1, 'order': 86, 'cost': 6, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_juggler', 'name': 'Juggler', 'rarity': 1, 'order': 87, 'cost': 4, 'set': 'Joker', 'config': {'h_size': 1}},
    {'key': 'j_drunkard', 'name': 'Drunkard', 'rarity': 1, 'order': 88, 'cost': 4, 'set': 'Joker', 'config': {'d_size': 1}},
    {'key': 'j_stone', 'name': 'Stone Joker', 'rarity': 2, 'order': 89, 'cost': 6, 'set': 'Joker', 'config': {'extra': 25}},
    {'key': 'j_golden', 'name': 'Golden Joker', 'rarity': 1, 'order': 90, 'cost': 6, 'set': 'Joker', 'config': {'extra': 4}},
    {'key': 'j_lucky_cat', 'name': 'Lucky Cat', 'rarity': 2, 'order': 91, 'cost': 6, 'set': 'Joker', 'config': {'Xmult': 1, 'extra': 0.25}},
    {'key': 'j_baseball', 'name': 'Baseball Card', 'rarity': 3, 'order': 92, 'cost': 8, 'set': 'Joker', 'config': {'extra': 1.5}},
    {'key': 'j_bull', 'name': 'Bull', 'rarity': 2, 'order': 93, 'cost': 6, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_diet_cola', 'name': 'Diet Cola', 'rarity': 2, 'order': 94, 'cost': 6, 'set': 'Joker', 'config': {}},
    {'key': 'j_trading', 'name': 'Trading Card', 'rarity': 2, 'order': 95, 'cost': 6, 'set': 'Joker', 'config': {'extra': 3}},
    {'key': 'j_flash', 'name': 'Flash Card', 'rarity': 2, 'order': 96, 'cost': 5, 'set': 'Joker', 'config': {'extra': 2, 'mult': 0}},
    {'key': 'j_popcorn', 'name': 'Popcorn', 'rarity': 1, 'order': 97, 'cost': 5, 'set': 'Joker', 'config': {'mult': 20, 'extra': 4}},
    {'key': 'j_trousers', 'name': 'Spare Trousers', 'rarity': 2, 'order': 98, 'cost': 6, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_ancient', 'name': 'Ancient Joker', 'rarity': 3, 'order': 99, 'cost': 8, 'set': 'Joker', 'config': {'extra': 1.5}},
    {'key': 'j_ramen', 'name': 'Ramen', 'rarity': 2, 'order': 100, 'cost': 6, 'set': 'Joker', 'config': {'Xmult': 2, 'extra': 0.01}},
    {'key': 'j_walkie_talkie', 'name': 'Walkie Talkie', 'rarity': 1, 'order': 101, 'cost': 4, 'set': 'Joker', 'config': {'extra': {'chips': 10, 'mult': 4}}},
    {'key': 'j_selzer', 'name': 'Seltzer', 'rarity': 2, 'order': 102, 'cost': 6, 'set': 'Joker', 'config': {'extra': 10}},
    {'key': 'j_castle', 'name': 'Castle', 'rarity': 2, 'order': 103, 'cost': 6, 'set': 'Joker', 'config': {'extra': {'chips': 0, 'chip_mod': 3}}},
    {'key': 'j_smiley', 'name': 'Smiley Face', 'rarity': 1, 'order': 104, 'cost': 4, 'set': 'Joker', 'config': {'extra': 5}},
    {'key': 'j_campfire', 'name': 'Campfire', 'rarity': 3, 'order': 105, 'cost': 9, 'set': 'Joker', 'config': {'extra': 0.25}},
    {'key': 'j_ticket', 'name': 'Golden Ticket', 'rarity': 1, 'order': 106, 'cost': 5, 'set': 'Joker', 'config': {'extra': 4}},
    {'key': 'j_mr_bones', 'name': 'Mr. Bones', 'rarity': 2, 'order': 107, 'cost': 5, 'set': 'Joker', 'config': {}},
    {'key': 'j_acrobat', 'name': 'Acrobat', 'rarity': 2, 'order': 108, 'cost': 6, 'set': 'Joker', 'config': {'extra': 3}},
    {'key': 'j_sock_and_buskin', 'name': 'Sock and Buskin', 'rarity': 2, 'order': 109, 'cost': 6, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_swashbuckler', 'name': 'Swashbuckler', 'rarity': 1, 'order': 110, 'cost': 4, 'set': 'Joker', 'config': {'mult': 1}},
    {'key': 'j_troubadour', 'name': 'Troubadour', 'rarity': 2, 'order': 111, 'cost': 6, 'set': 'Joker', 'config': {'extra': {'h_size': 2, 'h_plays': -1}}},
    {'key': 'j_certificate', 'name': 'Certificate', 'rarity': 2, 'order': 112, 'cost': 6, 'set': 'Joker', 'config': {}},
    {'key': 'j_smeared', 'name': 'Smeared Joker', 'rarity': 2, 'order': 113, 'cost': 7, 'set': 'Joker', 'config': {}},
    {'key': 'j_throwback', 'name': 'Throwback', 'rarity': 2, 'order': 114, 'cost': 6, 'set': 'Joker', 'config': {'extra': 0.25}},
    {'key': 'j_hanging_chad', 'name': 'Hanging Chad', 'rarity': 1, 'order': 115, 'cost': 4, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_rough_gem', 'name': 'Rough Gem', 'rarity': 2, 'order': 116, 'cost': 7, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_bloodstone', 'name': 'Bloodstone', 'rarity': 2, 'order': 117, 'cost': 7, 'set': 'Joker', 'config': {'extra': {'odds': 2, 'Xmult': 1.5}}},
    {'key': 'j_arrowhead', 'name': 'Arrowhead', 'rarity': 2, 'order': 118, 'cost': 7, 'set': 'Joker', 'config': {'extra': 50}},
    {'key': 'j_onyx_agate', 'name': 'Onyx Agate', 'rarity': 2, 'order': 119, 'cost': 7, 'set': 'Joker', 'config': {'extra': 7}},
    {'key': 'j_glass', 'name': 'Glass Joker', 'rarity': 2, 'order': 120, 'cost': 6, 'set': 'Joker', 'config': {'extra': 0.75, 'Xmult': 1}},
    {'key': 'j_ring_master', 'name': 'Showman', 'rarity': 2, 'order': 121, 'cost': 5, 'set': 'Joker', 'config': {}},
    {'key': 'j_flower_pot', 'name': 'Flower Pot', 'rarity': 2, 'order': 122, 'cost': 6, 'set': 'Joker', 'config': {'extra': 3}},
    {'key': 'j_blueprint', 'name': 'Blueprint', 'rarity': 3, 'order': 123, 'cost': 10, 'set': 'Joker', 'config': {}},
    {'key': 'j_wee', 'name': 'Wee Joker', 'rarity': 3, 'order': 124, 'cost': 8, 'set': 'Joker', 'config': {'extra': {'chips': 0, 'chip_mod': 8}}},
    {'key': 'j_merry_andy', 'name': 'Merry Andy', 'rarity': 2, 'order': 125, 'cost': 7, 'set': 'Joker', 'config': {'d_size': 3, 'h_size': -1}},
    {'key': 'j_oops', 'name': 'Oops! All 6s', 'rarity': 2, 'order': 126, 'cost': 4, 'set': 'Joker', 'config': {}},
    {'key': 'j_idol', 'name': 'The Idol', 'rarity': 2, 'order': 127, 'cost': 6, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_seeing_double', 'name': 'Seeing Double', 'rarity': 2, 'order': 128, 'cost': 6, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_matador', 'name': 'Matador', 'rarity': 2, 'order': 129, 'cost': 7, 'set': 'Joker', 'config': {'extra': 8}},
    {'key': 'j_hit_the_road', 'name': 'Hit the Road', 'rarity': 3, 'order': 130, 'cost': 8, 'set': 'Joker', 'config': {'extra': 0.5}},
    {'key': 'j_duo', 'name': 'The Duo', 'rarity': 3, 'order': 131, 'cost': 8, 'set': 'Joker', 'config': {'Xmult': 2, 'type': 'Pair'}},
    {'key': 'j_trio', 'name': 'The Trio', 'rarity': 3, 'order': 132, 'cost': 8, 'set': 'Joker', 'config': {'Xmult': 3, 'type': 'Three of a Kind'}},
    {'key': 'j_family', 'name': 'The Family', 'rarity': 3, 'order': 133, 'cost': 8, 'set': 'Joker', 'config': {'Xmult': 4, 'type': 'Four of a Kind'}},
    {'key': 'j_order', 'name': 'The Order', 'rarity': 3, 'order': 134, 'cost': 8, 'set': 'Joker', 'config': {'Xmult': 3, 'type': 'Straight'}},
    {'key': 'j_tribe', 'name': 'The Tribe', 'rarity': 3, 'order': 135, 'cost': 8, 'set': 'Joker', 'config': {'Xmult': 2, 'type': 'Flush'}},
    {'key': 'j_stuntman', 'name': 'Stuntman', 'rarity': 3, 'order': 136, 'cost': 7, 'set': 'Joker', 'config': {'extra': {'h_size': 2, 'chip_mod': 250}}},
    {'key': 'j_invisible', 'name': 'Invisible Joker', 'rarity': 3, 'order': 137, 'cost': 8, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_brainstorm', 'name': 'Brainstorm', 'rarity': 3, 'order': 138, 'cost': 10, 'set': 'Joker', 'config': {}},
    {'key': 'j_satellite', 'name': 'Satellite', 'rarity': 2, 'order': 139, 'cost': 6, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_shoot_the_moon', 'name': 'Shoot the Moon', 'rarity': 1, 'order': 140, 'cost': 5, 'set': 'Joker', 'config': {'extra': 13}},
    {'key': 'j_drivers_license', 'name': "Driver's License", 'rarity': 3, 'order': 141, 'cost': 7, 'set': 'Joker', 'config': {'extra': 3}},
    {'key': 'j_cartomancer', 'name': 'Cartomancer', 'rarity': 2, 'order': 142, 'cost': 6, 'set': 'Joker', 'config': {}},
    {'key': 'j_astronomer', 'name': 'Astronomer', 'rarity': 2, 'order': 143, 'cost': 8, 'set': 'Joker', 'config': {}},
    {'key': 'j_burnt', 'name': 'Burnt Joker', 'rarity': 3, 'order': 144, 'cost': 8, 'set': 'Joker', 'config': {'h_size': 0, 'extra': 4}},
    {'key': 'j_bootstraps', 'name': 'Bootstraps', 'rarity': 2, 'order': 145, 'cost': 7, 'set': 'Joker', 'config': {'extra': {'mult': 2, 'dollars': 5}}},
    {'key': 'j_caino', 'name': 'Caino', 'rarity': 4, 'order': 146, 'cost': 20, 'set': 'Joker', 'config': {'extra': 1}},
    {'key': 'j_triboulet', 'name': 'Triboulet', 'rarity': 4, 'order': 147, 'cost': 20, 'set': 'Joker', 'config': {'extra': 2}},
    {'key': 'j_yorick', 'name': 'Yorick', 'rarity': 4, 'order': 148, 'cost': 20, 'set': 'Joker', 'config': {'extra': {'xmult': 1, 'discards': 23}}},
    {'key': 'j_chicot', 'name': 'Chicot', 'rarity': 4, 'order': 149, 'cost': 20, 'set': 'Joker', 'config': {}},
    {'key': 'j_perkeo', 'name': 'Perkeo', 'rarity': 4, 'order': 150, 'cost': 20, 'set': 'Joker', 'config': {}},
]

CATALOG = [{'key': j['key'], 'name': j['name'], 'rarity': j['rarity'],
            'rarity_name': RARITIES.get(j['rarity'], 'Common')} for j in _JOKERS]
NAMES = {j['key']: j['name'] for j in _JOKERS}
CONFIGS = {j['key']: j for j in _JOKERS}


def name_for(center):
    return NAMES.get(center, center)
