; NSIS installer template. Values are injected via -D defines by installer-nsis.js.
Unicode True

!include "MUI2.nsh"
!include "FileFunc.nsh"
!include "LogicLib.nsh"

Name "${APPNAME}"
OutFile "${OUTFILE}"
InstallDir "$PROGRAMFILES64\${APPNAME}"
InstallDirRegKey HKLM "Software\${APPNAME}" "InstallDir"
; The E2E run installs into a temp folder without admin; releases always need admin.
!ifdef E2E_USER_LEVEL
  RequestExecutionLevel user
!else
  RequestExecutionLevel admin
!endif

!define MUI_ICON "${ICON}"
!define MUI_UNICON "${ICON}"
!define UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPNAME}"

; Signed builds (installer-nsis.js --sign) pass an include that Authenticode-signs Uninstall.exe.
!ifdef SIGN_INCLUDE
  !include "${SIGN_INCLUDE}"
!endif

; Generated by installer-nsis.js from the build folder: the RemoveAppFiles macro deletes
; exactly the app's own top-level files and folders, nothing else in $INSTDIR.
!include "${APP_FILES_INCLUDE}"

!insertmacro MUI_PAGE_WELCOME
!define MUI_PAGE_CUSTOMFUNCTION_LEAVE DirectoryLeave
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

; Always install into a folder of our own, so a typed path like D:\Games becomes
; D:\Games\Balatro Save Editor and never mixes with other files.
Function EnsureOwnFolder
  StrCpy $0 "$INSTDIR" 1 -1
  ${If} $0 == "\"
    StrCpy $INSTDIR "$INSTDIR" -1
  ${EndIf}
  ${GetFileName} "$INSTDIR" $0
  ${If} $0 != "${APPNAME}"
    StrCpy $INSTDIR "$INSTDIR\${APPNAME}"
  ${EndIf}
FunctionEnd

Function .onInit
  Call EnsureOwnFolder
FunctionEnd

Function DirectoryLeave
  Call EnsureOwnFolder
FunctionEnd

; A running copy keeps its exe locked; stop instead of half-overwriting it.
; Used once per section, so the label is unique within each.
!macro WaitForAppClosed
  ${If} ${FileExists} "$INSTDIR\${EXENAME}"
    app_running_check:
    ClearErrors
    FileOpen $0 "$INSTDIR\${EXENAME}" a
    ${If} ${Errors}
      MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION "${APPNAME} is running. Close it, then press Retry." /SD IDCANCEL IDRETRY app_running_check
      Abort "${APPNAME} is running."
    ${EndIf}
    FileClose $0
  ${EndIf}
!macroend

; 1.0.0 created its shortcuts in the installing user's profile; drop those so the app
; isn't listed twice next to the all-users ones.
!macro RemoveUserShortcuts
  SetShellVarContext current
  Delete "$SMPROGRAMS\${APPNAME}.lnk"
  Delete "$DESKTOP\${APPNAME}.lnk"
  SetShellVarContext all
!macroend

Section "Install"
  !insertmacro RemoveUserShortcuts
  !insertmacro WaitForAppClosed
  ; Upgrading: clear the previous version's files so nothing stale is left behind.
  ${If} ${FileExists} "$INSTDIR\${EXENAME}"
    !insertmacro RemoveAppFiles
  ${EndIf}
  SetOutPath "$INSTDIR"
  File /r "${SOURCE_DIR}\*.*"

  WriteRegStr HKLM "Software\${APPNAME}" "InstallDir" "$INSTDIR"
  CreateShortcut "$SMPROGRAMS\${APPNAME}.lnk" "$INSTDIR\${EXENAME}"
  CreateShortcut "$DESKTOP\${APPNAME}.lnk" "$INSTDIR\${EXENAME}"
  WriteUninstaller "$INSTDIR\Uninstall.exe"

  WriteRegStr HKLM "${UNINST_KEY}" "DisplayName" "${APPNAME}"
  WriteRegStr HKLM "${UNINST_KEY}" "DisplayVersion" "${VERSION}"
  WriteRegStr HKLM "${UNINST_KEY}" "Publisher" "${PUBLISHER}"
  WriteRegStr HKLM "${UNINST_KEY}" "DisplayIcon" "$INSTDIR\${EXENAME}"
  WriteRegStr HKLM "${UNINST_KEY}" "UninstallString" "$INSTDIR\Uninstall.exe"
SectionEnd

Section "Uninstall"
  !insertmacro RemoveUserShortcuts
  !insertmacro WaitForAppClosed
  Delete "$SMPROGRAMS\${APPNAME}.lnk"
  Delete "$DESKTOP\${APPNAME}.lnk"
  !insertmacro RemoveAppFiles
  Delete "$INSTDIR\Uninstall.exe"
  ; Not /r: anything the user added stays, and so does the folder then.
  RMDir "$INSTDIR"
  DeleteRegKey HKLM "Software\${APPNAME}"
  DeleteRegKey HKLM "${UNINST_KEY}"
SectionEnd
